# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-toml
    -   id: check-vcs-permalinks
-   repo: https://github.com/ansg191/pre-commit-rust
    rev: v1.1
    hooks:
        -   id: fmt
        -   id: cargo-check
        -   id: clippy
